export const SET_SNACKBAR = 'SET_SNACKBAR';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_REGISTRATION = 'REQUEST_REGISTRATION';
export const SET_TOKEN = 'SET_TOKEN';
export const CLEAR_TOKEN = 'CLEAR_TOKEN';

export const SET_FULL_NAME = 'SET_FULL_NAME';
export const CLEAR_USER = 'CLEAR_USER';

export const ADD_COURSE = 'ADD_COURSE';
export const FETCH_COURSES = 'FETCH_COURSES';
export const SAVE_COURSES = 'SAVE_COURSES';
export const CLEAR_FETCHED_COURSES = 'CLEAR_FETCHED_COURSES';
export const FETCH_ONE_COURSE = 'FETCH_ONE_COURSE';
export const SAVE_ONE_COURSE = 'SAVE_ONE_COURSE';
export const EDIT_ONE_COURSE = 'EDIT_ONE_COURSE';
export const CLEAR_ONE_COURSE = 'CLEAR_ONE_COURSE';
export const REMOVE_ONE_COURSE = 'REMOVE_ONE_COURSE';
export const FETCH_LESSON = 'FETCH_LESSON';
export const SET_LESSON = 'SET_LESSON';
export const CLEAR_LESSON = 'CLEAR_LESSON';

export const START_FETCHING = 'START_FETCHING';
export const STOP_FETCHING = 'STOP_FETCHING';
export const FILL_FETCHED = 'FILL_FETCHED';
export const SET_FETCHING_ERROR = 'SET_FETCHING_ERROR';
export const RESET_SPINNER = 'RESET_SPINNER';
