export const SET_SNACKBAR = 'SET_SNACKBAR';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_REGISTRATION = 'REQUEST_REGISTRATION';
export const SET_TOKEN = 'SET_TOKEN';
export const CLEAR_TOKEN = 'CLEAR_TOKEN';

export const SET_FULL_NAME = 'SET_FULL_NAME';

export const ADD_COURSE = 'ADD_COURSE';
export const REMOVE_COURSE = 'REMOVE_COURSE_IN_USER';
export const EDIT_COURSE = 'EDIT_COURSE';
export const SAVE_COURSES = 'SAVE_COURSES';
export const RESET_COURSE = 'RESET_COURSE';

export const START_FETCHING = 'START_FETCHING';
export const STOP_FETCHING = 'STOP_FETCHING';
export const FILL_FETCHED = 'FILL_FETCHED';
export const SET_FETCHING_ERROR = 'SET_FETCHING_ERROR';
export const RESET_SPINNER = 'RESET_SPINNER';
